"""initial schema

Revision ID: 708a038b96f4
Revises: 
Create Date: 2026-08-07 20:40:36.644608
"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '708a038b96f4'
down_revision: Optional[str] = None
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('draft', 'extracting', 'reviewing', 'exporting', 'completed', 'failed', name='job_status', native_enum=False, create_constraint=True), server_default='draft', nullable=False),
    sa.Column('original_excel_path', sa.String(length=1024), nullable=True),
    sa.Column('original_excel_name', sa.String(length=255), nullable=True),
    sa.Column('original_excel_sha256', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('result_path', sa.String(length=1024), nullable=True),
    sa.Column('failure_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_original_excel_sha256'), 'jobs', ['original_excel_sha256'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('source_order', sa.Integer(), nullable=False),
    sa.Column('original_image_path', sa.String(length=1024), nullable=False),
    sa.Column('original_image_name', sa.String(length=255), nullable=False),
    sa.Column('corrected_image_path', sa.String(length=1024), nullable=True),
    sa.Column('image_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='document_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('photo_supplier', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('document_total', sa.Integer(), nullable=True),
    sa.Column('raw_header_text', sa.Text(), nullable=True),
    sa.Column('confidence_by_field', sa.JSON(), nullable=False),
    sa.Column('model_response', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('duplicate_status', sa.Enum('none', 'suspected', 'confirmed', name='duplicate_status', native_enum=False, create_constraint=True), server_default='none', nullable=False),
    sa.Column('document_identity_key', sa.String(length=512), nullable=True),
    sa.Column('item_signature', sa.String(length=64), nullable=True),
    sa.Column('processing_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('document_total IS NULL OR document_total >= 0', name=op.f('ck_documents_document_total_nonnegative')),
    sa.CheckConstraint('source_order >= 0', name=op.f('ck_documents_source_order_nonnegative')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_documents_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('job_id', 'source_order', name='uq_documents_job_source_order')
    )
    op.create_index(op.f('ix_documents_document_identity_key'), 'documents', ['document_identity_key'], unique=False)
    op.create_index(op.f('ix_documents_duplicate_status'), 'documents', ['duplicate_status'], unique=False)
    op.create_index(op.f('ix_documents_image_sha256'), 'documents', ['image_sha256'], unique=False)
    op.create_index(op.f('ix_documents_item_signature'), 'documents', ['item_signature'], unique=False)
    op.create_index(op.f('ix_documents_job_id'), 'documents', ['job_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('completed_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=False),
    sa.Column('document_identity_key', sa.String(length=512), nullable=True),
    sa.Column('item_signature', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_completed_documents_job_id_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_completed_documents_source_document_id_documents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_completed_documents')),
    sa.UniqueConstraint('source_document_id', name=op.f('uq_completed_documents_source_document_id'))
    )
    op.create_index(op.f('ix_completed_documents_document_identity_key'), 'completed_documents', ['document_identity_key'], unique=False)
    op.create_index(op.f('ix_completed_documents_image_sha256'), 'completed_documents', ['image_sha256'], unique=False)
    op.create_index(op.f('ix_completed_documents_item_signature'), 'completed_documents', ['item_signature'], unique=False)
    op.create_index(op.f('ix_completed_documents_job_id'), 'completed_documents', ['job_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('source_row_order', sa.Integer(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('raw_row_text', sa.Text(), nullable=True),
    sa.Column('ocr_product_code_or_barcode', sa.String(length=100), nullable=True),
    sa.Column('ocr_product_name', sa.String(length=255), nullable=True),
    sa.Column('ocr_specification', sa.String(length=255), nullable=True),
    sa.Column('ocr_quantity', sa.Integer(), nullable=True),
    sa.Column('ocr_unit_price', sa.Integer(), nullable=True),
    sa.Column('ocr_amount', sa.Integer(), nullable=True),
    sa.Column('ocr_bundle_or_set_text', sa.String(length=255), nullable=True),
    sa.Column('ocr_confidence_by_field', sa.JSON(), nullable=False),
    sa.Column('extraction_warnings', sa.JSON(), nullable=False),
    sa.Column('product_code_or_barcode', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('specification', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('bundle_or_set_text', sa.String(length=255), nullable=True),
    sa.Column('stock_increment', sa.Integer(), nullable=True),
    sa.Column('matched_product_code', sa.String(length=100), nullable=True),
    sa.Column('matched_product_name', sa.String(length=255), nullable=True),
    sa.Column('matched_specification', sa.String(length=255), nullable=True),
    sa.Column('matched_supplier_code', sa.String(length=100), nullable=True),
    sa.Column('matched_supplier', sa.String(length=255), nullable=True),
    sa.Column('matched_excel_row', sa.Integer(), nullable=True),
    sa.Column('match_method', sa.Enum('code', 'normalized_name_spec', 'similarity', 'manual', name='match_method', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_candidates', sa.JSON(), nullable=False),
    sa.Column('base_stock', sa.Integer(), nullable=True),
    sa.Column('base_purchase_price', sa.Integer(), nullable=True),
    sa.Column('apply_inventory', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('apply_purchase_price', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('review_status', sa.Enum('pending', 'approved', 'excluded', name='review_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('exclusion_reason', sa.String(length=500), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("review_status != 'approved' OR (matched_product_code IS NOT NULL AND stock_increment IS NOT NULL)", name=op.f('ck_items_approved_requires_match_and_stock')),
    sa.CheckConstraint("review_status != 'excluded' OR (exclusion_reason IS NOT NULL AND length(trim(exclusion_reason)) > 0)", name=op.f('ck_items_excluded_requires_reason')),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name=op.f('ck_items_amount_nonnegative')),
    sa.CheckConstraint('base_purchase_price IS NULL OR base_purchase_price >= 0', name=op.f('ck_items_base_purchase_price_nonnegative')),
    sa.CheckConstraint('quantity IS NULL OR quantity >= 0', name=op.f('ck_items_quantity_nonnegative')),
    sa.CheckConstraint('source_row_order >= 0', name=op.f('ck_items_source_row_order_nonnegative')),
    sa.CheckConstraint('stock_increment IS NULL OR stock_increment >= 0', name=op.f('ck_items_stock_increment_nonnegative')),
    sa.CheckConstraint('unit_price IS NULL OR unit_price >= 0', name=op.f('ck_items_unit_price_nonnegative')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_items_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items'))
    )
    op.create_index(op.f('ix_items_document_id'), 'items', ['document_id'], unique=False)
    op.create_index(op.f('ix_items_matched_product_code'), 'items', ['matched_product_code'], unique=False)
    op.create_index(op.f('ix_items_review_status'), 'items', ['review_status'], unique=False)
    op.create_table('price_resolutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('resolution_method', sa.Enum('unresolved', 'automatic', 'manual', name='resolution_method', native_enum=False, create_constraint=True), server_default='unresolved', nullable=False),
    sa.Column('selected_item_id', sa.String(length=36), nullable=True),
    sa.Column('selected_unit_price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("resolution_method = 'unresolved' OR selected_unit_price IS NOT NULL", name=op.f('ck_price_resolutions_resolved_requires_price')),
    sa.CheckConstraint('selected_unit_price IS NULL OR selected_unit_price >= 0', name=op.f('ck_price_resolutions_selected_unit_price_nonnegative')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_price_resolutions_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_item_id'], ['items.id'], name=op.f('fk_price_resolutions_selected_item_id_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_resolutions')),
    sa.UniqueConstraint('job_id', 'product_code', name='uq_price_resolutions_job_product'),
    sa.UniqueConstraint('selected_item_id', name=op.f('uq_price_resolutions_selected_item_id'))
    )
    op.create_index(op.f('ix_price_resolutions_job_id'), 'price_resolutions', ['job_id'], unique=False)
    op.create_index(op.f('ix_price_resolutions_product_code'), 'price_resolutions', ['product_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_resolutions_product_code'), table_name='price_resolutions')
    op.drop_index(op.f('ix_price_resolutions_job_id'), table_name='price_resolutions')
    op.drop_table('price_resolutions')
    op.drop_index(op.f('ix_items_review_status'), table_name='items')
    op.drop_index(op.f('ix_items_matched_product_code'), table_name='items')
    op.drop_index(op.f('ix_items_document_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_completed_documents_job_id'), table_name='completed_documents')
    op.drop_index(op.f('ix_completed_documents_item_signature'), table_name='completed_documents')
    op.drop_index(op.f('ix_completed_documents_image_sha256'), table_name='completed_documents')
    op.drop_index(op.f('ix_completed_documents_document_identity_key'), table_name='completed_documents')
    op.drop_table('completed_documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_job_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_item_signature'), table_name='documents')
    op.drop_index(op.f('ix_documents_image_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_duplicate_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_identity_key'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_original_excel_sha256'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
