"""add product index

Revision ID: b4c956721987
Revises: 708a038b96f4
Create Date: 2026-08-07 20:51:06.494204
"""
from typing import Optional, Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b4c956721987'
down_revision: Optional[str] = '708a038b96f4'
branch_labels: Optional[Union[str, Sequence[str]]] = None
depends_on: Optional[Union[str, Sequence[str]]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_index',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('product_code', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('specification', sa.String(length=500), nullable=True),
    sa.Column('current_stock', sa.JSON(), nullable=True),
    sa.Column('purchase_price', sa.JSON(), nullable=True),
    sa.Column('supplier_code', sa.String(length=255), nullable=True),
    sa.Column('supplier', sa.String(length=500), nullable=True),
    sa.Column('excel_row', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('excel_row >= 2', name=op.f('ck_product_index_excel_row_after_header')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_product_index_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_index')),
    sa.UniqueConstraint('job_id', 'excel_row', name='uq_product_index_job_excel_row'),
    sa.UniqueConstraint('job_id', 'product_code', name='uq_product_index_job_product')
    )
    op.create_index(op.f('ix_product_index_job_id'), 'product_index', ['job_id'], unique=False)
    op.create_index(op.f('ix_product_index_product_code'), 'product_index', ['product_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_index_product_code'), table_name='product_index')
    op.drop_index(op.f('ix_product_index_job_id'), table_name='product_index')
    op.drop_table('product_index')
    # ### end Alembic commands ###
